model_list:
  - model_name: "azure-gpt5-nano"
    litellm_params:
      model: "azure/gpt-5-nano"
      api_base: "https://YOUR_AZURE_RESOURCE.openai.azure.com/"
      api_key: "os.environ/AZURE_API_KEY"
      api_version: "2024-05-01-preview"

  - model_name: "bedrock-nova"
    litellm_params:
      model: "bedrock/amazon.nova-micro-v1:0"

    router_settings:
      model_group_alias:
        "nova-bedrock": "bedrock-nova"
        "gpt-azure": "azure-gpt5-nano"
        "default": "azure-gpt5-nano"
